module.exports = {
  devdeps: [
    '@types/jest',
    '@types/node',
    '@types/source-map-support',
    'eslint',
    'husky',
    'jest',
    'prettier',
    'pretty-quick',
    'rimraf',
    'ts-jest',
    'typescript',
    '@typescript-eslint/eslint-plugin',
    '@typescript-eslint/parser',
    'eslint-config-prettier',
    'eslint-plugin-prettier',
    'eslint-plugin-react',
  ],
  deps: ['source-map-support', 'tslib'],
}
